// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9aPmQ7zpNZH2iaf6bDQT0JlMIO_LEEo0',
    appId: '1:1094907899525:web:108ec764777488cae283ec',
    messagingSenderId: '1094907899525',
    projectId: 'test-8f1b5',
    authDomain: 'test-8f1b5.firebaseapp.com',
    databaseURL: 'https://test-8f1b5-default-rtdb.firebaseio.com',
    storageBucket: 'test-8f1b5.appspot.com',
    measurementId: 'G-41G6C89K9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5vCIWcovlNcFwgWqTYVoFrkaDEbSZXQs',
    appId: '1:1094907899525:android:468b28d182933f41e283ec',
    messagingSenderId: '1094907899525',
    projectId: 'test-8f1b5',
    databaseURL: 'https://test-8f1b5-default-rtdb.firebaseio.com',
    storageBucket: 'test-8f1b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjbsOjlSOea21lC4Cu7d84RlE6Qt9xC8g',
    appId: '1:1094907899525:ios:43a5234009e6e1abe283ec',
    messagingSenderId: '1094907899525',
    projectId: 'test-8f1b5',
    databaseURL: 'https://test-8f1b5-default-rtdb.firebaseio.com',
    storageBucket: 'test-8f1b5.appspot.com',
    iosClientId: '1094907899525-mco0d4s3frkf3og5fvvnkblf5phmdt3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.g12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjbsOjlSOea21lC4Cu7d84RlE6Qt9xC8g',
    appId: '1:1094907899525:ios:43a5234009e6e1abe283ec',
    messagingSenderId: '1094907899525',
    projectId: 'test-8f1b5',
    databaseURL: 'https://test-8f1b5-default-rtdb.firebaseio.com',
    storageBucket: 'test-8f1b5.appspot.com',
    iosClientId: '1094907899525-mco0d4s3frkf3og5fvvnkblf5phmdt3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.g12',
  );
}
